### PR TITLE
Rspec models product

### PR DESCRIPTION
**Pull request by tvquy17it3**
## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by tvquy17it3** [comment]
ready

**Comment by vanvtt-0952** [comment]
merged

**Pull request merged**
