### PR TITLE
User remove product cart

### PR DESCRIPTION
**Pull request by ntthang1121**
## Related Tickets
- [#42989](https://edu-redmine.sun-asterisk.vn/issues/42989)

## WHAT (optional)
- User remove product cart

## Evidence (Screenshot or Video)
image
image

### CODE REVIEW

**Review by KhanhPV99 — APPROVED** [review]

**Comment by ntthang1121** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
fix conflict lẹ nhé
để chị chia pull luon

**Comment by ntthang1121** [comment]
ready

**Comment by vanvtt-0952** [comment]
merged
hết pull rồi đúng hok em

**Pull request merged**
